insert into MONTHLY_MASTER_BK_CHANGED_ATTR_INTERVIEW values('33TST2','NEW','125cc','2016','Minibike','INDIA','N','J','RWD',1,0);
insert into MONTHLY_MASTER_BK_CHANGED_ATTR_INTERVIEW values('33TST1','NEW','800cc','2015','DUAL','ITA','Z','P','RWD',1,0);
